# Generated by Django 4.2.5 on 2023-10-17 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.movie', to_field='movie_id'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_movies',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='reviews.movie'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_reviews',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rated_movies',
            field=models.ManyToManyField(blank=True, related_name='rated_by', to='reviews.movie'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rated_reviews',
            field=models.ManyToManyField(blank=True, related_name='rated_by', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_comments',
            field=models.ManyToManyField(blank=True, related_name='commented_by', to='reviews.comment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_reviews',
            field=models.ManyToManyField(blank=True, related_name='reviewed_by', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
