# Generated by Django 5.2.7 on 2025-10-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_verification_datetime_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
