# Generated by Django 5.2.7 on 2025-10-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_social_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social',
            field=models.ManyToManyField(to='users.social'),
        ),
    ]
