# Generated by Django 5.2.7 on 2025-10-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
