# Generated by Django 5.2.7 on 2025-10-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_social_link_alter_social_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(default='https://example.com/default'),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(default='default social'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social',
            field=models.ManyToManyField(blank=True, to='users.social'),
        ),
    ]
