# Generated by Django 5.2.7 on 2025-12-06 21:19

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(validators=[reviews.models.validate_star_length]),
        ),
    ]
