# Generated by Django 5.2.7 on 2025-12-10 03:43

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_rating_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveIntegerField(validators=[reviews.models.validate_star_length]),
        ),
    ]
