# Generated by Django 5.2.7 on 2025-12-10 09:31

import reviews.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_rating_stars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(reviews.models.get_deleted_user), related_name='rated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
