# Generated by Django 5.2.7 on 2025-12-10 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_rating_review_alter_rating_movie_alter_rating_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
        ),
    ]
